Debug information for file: javali_tests/HW1/Test1.javali

Test failed because an exception was thrown:
    Parse failure on line 0: ?
Stack trace:
cd.frontend.parser.ParseFailure: Parse failure on line 0: ?
	at cd.Main.parse(Main.java:96)
	at cd.test.AbstractTestAgainstFrozenReference.testParser(AbstractTestAgainstFrozenReference.java:108)
	at cd.test.AbstractTestAgainstFrozenReference.test(AbstractTestAgainstFrozenReference.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
	at org.antlr.v4.runtime.Parser.match(Parser.java:223)
	at cd.frontend.parser.JavaliParser.a(Unknown Source)
	at cd.frontend.parser.JavaliParser.a(Unknown Source)
	at cd.frontend.parser.JavaliParser.a(Unknown Source)
	at cd.frontend.parser.JavaliParser.unit(Unknown Source)
	at cd.Main.parse(Main.java:90)
	... 14 more
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	... 20 more
